#!/bin/bash

cd ${HOME}/openxt

. openxt-env $@

while read line; do
  m=$(echo $line|cut -f1 -d' ')
  i=$(echo $line|cut -f2 -d' ')
  MACHINE=$m bb $i || {
    echo -ne "\a"
    break
  }
done <<EOF  
xenclient-dom0 xenclient-initramfs-image
xenclient-stubdomain xenclient-stubdomain-initramfs-image
xenclient-dom0 xenclient-dom0-image
xenclient-uivm xenclient-uivm-image
xenclient-ndvm xenclient-ndvm-image
xenclient-dom0 xenclient-installer-image
xenclient-dom0 xenclient-installer-part2-image
EOF

