#!/bin/bash
#
# Copyright (c) 2016 Apertus Solutions, LLC
#
# Contributions by Daniel P. Smith
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#


BUILD_ID=${1}
if [ -z "${BUILD_ID}" ]; then
    echo "Please provide the build id you would like to package"
    exit 1
fi

# expecting to be in ${TOP}/bin
TOP=$(readlink -f "$(dirname $(readlink -f $_))")

TARGET_DIR=${2:-"${TOP}/deploy-${BUILD_ID}"}
DEPLOY_DIR="${TOP}/build-${BUILD_ID}/tmp-glibc/deploy"

if [ ! -d "${DEPLOY_DIR}" ]; then
    echo "Cannot locate OE deploy directory for build"
    exit 1
fi

if [ -d "${TARGET_DIR}" ]; then
    echo "Deploy directory already exists!"
    exit 1
fi

# setup structure
mkdir -p "${TARGET_DIR}"/{packages.main,isolinux,netboot,licenses,sdk}

# copy installer related files
for f in $(find "${DEPLOY_DIR}/images/openxt-installer"); do
    case $f in
        */iso/*)
            cp "$f" "${TARGET_DIR}/isolinux/." ;;
        *tboot.gz)
            cp "$f" "${TARGET_DIR}/isolinux/." ;;
        *xen.gz)
            cp "$f" "${TARGET_DIR}/isolinux/." ;;
        *bzImage)
            cp "$f" "${TARGET_DIR}/isolinux/vmlinuz" ;;
        *microcode_intel.bin)
            cp "$f" "${TARGET_DIR}/isolinux/." ;;
        *.acm)
            cp "$f" "${TARGET_DIR}/isolinux/." ;;
        *xenclient-installer-image-openxt-installer.cpio.gz)
            cp "$f" "${TARGET_DIR}/isolinux/rootfs.gz" ;;
        *xenclient-installer-part2-image-openxt-installer.tar.bz2)
            cp "$f" "${TARGET_DIR}/packages.main/control.tar.bz2" ;;
        */netboot/*)
            cp "$f" "${TARGET_DIR}/netboot/." ;;
    esac
done

# copy any domain images
for f in $(find "${DEPLOY_DIR}/images" -type l -name '*.ext3.vhd.gz' -o -name '*.ext3.gz'); do
    domain=$(basename "$f" | cut -f2 -d-) 

    case $f in
        *.ext3.gz)
            cp "$f" "${TARGET_DIR}/packages.main/${domain}-rootfs.i686.ext3.gz" ;;
        *.vhd.gz)
            cp "$f" "${TARGET_DIR}/packages.main/${domain}-rootfs.i686.ext3.vhd.gz" ;;
    esac
done

# copy the licenses csv files
find "${DEPLOY_DIR}/images" -name '*-licences.csv' -exec cp {} "${TARGET_DIR}/licenses/." \;

# symlink ipk into directory
ln -s "${DEPLOY_DIR}/ipk" "${TARGET_DIR}/."

# push in tarball of sdk files
[ -d "${TOP}/openxt/sdk" ] &&
    tar --exclude=.git --owner=100 --group=100 \
        -hzcf "${TOP}/openxt/sdk" "${TARGET_DIR}/sdk/openxt-sdk.tar.gz"

