#!/bin/bash

check_subject() {
	local cert=$1
	local subj=$2

	local old_subj=$(openssl x509 -noout -subject -in "${cert}" |
		sed -n '/^subject/s/^subject=\s\+//p')
	
	[ "${subj}" == "${old_subj}" ] || return 1
}

gen_cert() {
	local cert=$1
	local subj=$2

	local d=$(dirname "${cert}")
	local b=$(basename "${cert}")

	[ -d "${d}" ] || mkdir -p "${d}"

	openssl genrsa -out "${d}/${b}key.pem" 2048
	openssl req -new -x509 -key "${d}/${b}key.pem" -out "${cert}cert.pem" -days 1095 \
	    -subj "${subj}"
}

SUBJECT="/C=US/ST=Massachusetts/L=Boston/O=OpenXT/OU=OpenXT/CN=openxt.org"

while getopts ":s:" opt; do
	case "$opt" in
		s) SUBJECT="${OPTARG}" ;;
	esac
done

shift "$((OPTIND-1))"

CERT_PATH=${1:-"${HOME}/certs"}

for c in dev-ca prod-ca; do
	if [ -e "${CERT_PATH}/${c}cert.pem" ]; then
		if check_subject "${CERT_PATH}/${c}cert.pem" "${SUBJECT}"; then
			continue;
		else
			rm "${CERT_PATH}/${c}"{cert,key}.pem
			gen_cert "${CERT_PATH}/${c}" "${SUBJECT}"
		fi
	else
		gen_cert "${CERT_PATH}/${c}" "${SUBJECT}"
	fi
done
